#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace AStar
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ grid;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xRow;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xCol;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xStart;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xEnd;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xStep;
        private: ::Windows::UI::Xaml::Controls::Button^ xInitialize;
        private: ::Windows::UI::Xaml::Controls::Button^ xCompute;
        private: ::Windows::UI::Xaml::Controls::Button^ xReset;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ xLog;
    };
}

